### ISSUE TITLE
Bug: Making someone a presenter does not change the text and can be granted again and again

### ISSUE THREAD

**Issue by rabitem** [Anapher/Strive#2]
If I make a user a presenter in my room, I should not be able to do this again afterwards. The text should change afterwards (for example to: take away presenter or similar as desired). Steps to replicate:

1. make someone a presenter
2. after that he can be made presenter any number of times

**Comment by Anapher** [comment]
Hey,
thanks for your report, I really appreciate it. You are totally right, I will fix this at the weekend as i’m currently on vacation.

If I may ask, how did you get to know about this project? :)

**Comment by rabitem** [comment]
Hi,

Gerne doch. Ich denke wir können das ganze hier auch auf Deutsch machen! Ich bin ein Freund von Titus und auch in der IT tätig. Das Projekt habe ich mir mal genauer angeschaut, da ich die Idee ganz cool fand. Vieles kam mir bekannt vor und dann habe ich mal ein bisschen rumgespielt. 

Liebe Grüße und schönen Urlaub dir,
Felix Huisinga
