### ISSUE TITLE
[Request]: Add .env.example for the node SFU

### ISSUE THREAD

**Issue by heyitzkamal** [Anapher/Strive#5]
Title says it all

**Comment by Anapher** [comment]
Hey,
the SFU doesn't actually need an environment file, you can change the configuration in the [config.ts file](https://github.com/Anapher/Strive/blob/a6830febea279bc770a0c642aa6ddb7e55ebd360/src/Services/SFU/src/config.ts). If you want to know how you can configure the environment variables for deployment, you can find an example in the [docker-compose.override.yml](https://github.com/Anapher/Strive/blob/develop/src/docker-compose.override.yml) and [docker-compose.prod.yml](https://github.com/Anapher/Strive/blob/develop/src/docker-compose.prod.yml) files.

Does that help you?

**Comment by heyitzkamal** [comment]
Absolutely. Thank you
