### ISSUE TITLE
[Feature] How to Implements Load Balance

### ISSUE THREAD

**Issue by engru** [Anapher/Strive#6]
Hi, the feature support load balance .
I have read the code , but still have no idea how to deploy load balance .
can anyone give me some tips ?

> If I want to deploy in kubernetes , How should I do ?
> I think it might be very hard, the k8s don't support port range now

**Comment by Anapher** [comment]
Hey,
you're right that load balancing is not trivial for Strive for two reasons: the media transmission is stateful and there are special requirement for WebRTC (public ip address must be known and the port range).
Here you can find a discussion about deploying BigBlueButton to Kubernetes: https://groups.google.com/g/bigbluebutton-dev/c/726_8n8bKxI they sadly come to the conclusion that the port ranges issue cannot be solved :/

You can find some discussions about mediasoup deployment to kubernetes here: https://groups.google.com/g/mediasoup/c/c6R3ZMqKBmM I think one of them is using Docker Swarm which does support port ranges, idk.

At least Kubernetes is actively working on this issue: https://github.com/kubernetes/enhancements/pull/2611

While deploying the SFU using Kubernetes may seem hard, manual deployment would actually work but I don't know if that's an option for you. Sorry :/

**Comment by engru** [comment]
thanks, i got it
