### ISSUE TITLE
Full Screen mode

### ISSUE THREAD

**Issue by deflax** [Anapher/Strive#7]
Hello. I am wondering is it possible as a client to force full screen on any of the remote screens? I was searching for the button but couldnt find any :)

Apart from that I really like how many management features are already in mind, so keep up the good work :)

**Comment by deflax** [comment]
Ah sorry. i found that its planned: https://github.com/Anapher/Strive/projects/1#card-58767612

closing :)

**Comment by Anapher** [comment]
Hey,
the feature that is planned is a custom interface where I want to hide unnecessary things like the title bar etc., much like Zoom fullscreen.

If that’s not what you mean: when you select a participant as presenter, and this participant activates screen sharing, he will automatically be focused. Also, you can always select the active remote screen as a moderator.
It was a design decision for me that all participants always see the same screen (same scene), so it’s not possible that in one room, multiple participants can share their screen.

**Comment by deflax** [comment]
When i tested bbb before, i was able to share screen on 1080p so the rest of the participants can just view that on full screen. It was without any loss of quality which was rly nice. In mirotalk-sfu i noticed how that works with single click on any videobox which was nice feature. Sure focusing the view is one of the best features here, but its limited to just having a bigger window, which still wont work with tiny text shares.

**Comment by Anapher** [comment]
Hey,
now I understand your issue. You were right, this is currently on the todo list. Please note that Strive does also transmit the video in 1080p, but you are also right that we really need the feature to have the screen share video the same size as the browser window. I will work on it
